name: xcodebuild

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: build
      run: xcodebuild -project "Ample.xcodeproj" -target "Ample Lite" | xcpretty

    - uses: actions/upload-artifact@v4
      with:
        name: Ample Lite
        path: build/Release/
