name: xcodebuild

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: build
      run: xcodebuild -project "Ample.xcodeproj" -target "Ample Lite" | xcpretty

